### ISSUE TITLE
If the workflow_id contains special characters (in particular @ or : ) is not possible to access its details (404)

### ISSUE THREAD

**Issue by marimp** [temporalio/ui#1084]
**Describe the bug**
If the workflow_id contains special characters (in particular @ or : ) is not possible to access its details (404)

**To Reproduce**
I'm using temporal server 1.18.5 and I tried the following UI versions:

2.7.1
2.10.0 (latest)

1. Go to temporal ui
2. Click on 'a workflow for example "**parent:Portal:A9892eade-a75d-4b5d-aaaf-aba7dedbf966**"
3. See error

```
404

Uh oh. There's an error.

Workflow executionsRow not found. WorkflowId: parent%3APortal%3A9892eade-a75d-4b5d-aaaf-aba7dedbf966, RunId: b728b371-6b59-42e2-afea-682a00ed06d4

[Try a refresh](https://wfe-engine-svil.cloud.bankit.it:8088/namespaces/sddc-portal/workflows/parent%3APortal%3A9892eade-a75d-4b5d-aaaf-aba7dedbf966/b728b371-6b59-42e2-afea-682a00ed06d4/history) or [jump on our Slack Channel](https://temporal.io/slack).
```

By accessing a workflow with no special characters no error is reported 

**Expected behavior**
No Error

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox 91.11, Edge

**Additional context**
Impatted versions:
Temporal UI Version >= 2.7.1
2.10.0 is still impacted

I opened this issue after suggestion of upgrading UI version to 2.10.0
[slack](https://temporalio.slack.com/archives/CTRCR8RBP/p1674751939304329?thread_ts=1674748317.120939&cid=CTRCR8RBP)

**Comment by rossedfort** [comment]
Hey @marimp could you tell me how you are getting to this page? `https://wfe-engine-svil.cloud.bankit.it:8088/namespaces/sddc-portal/workflows/parent%3APortal%3A9892eade-a75d-4b5d-aaaf-aba7dedbf966/b728b371-6b59-42e2-afea-682a00ed06d4/history` Are you on the Recent Workflows page and clicking on a Workflow Execution from the table? Or is there another way you are getting there? Additionally, could you try replacing `%3A` with `:` in the url via the address bar of your browser and trying to load the page? Thanks!

**Comment by marimp** [comment]
Hi, 
I tried by the workflow table and also with the direct link bu using both "%3A" an ":" same issue.
Should it be related to there portal server version? I upgraded to 1.18.5

**Comment by rossedfort** [comment]
Ok great, thanks for trying. I think the issue is definitely isolated to the UI and UI Server, upgrading the Temporal Server version likely will not resolve the issue. It's likely specific to Windows/Firefox, I'll keep digging in and keep you updated in this thread.

**Comment by rossedfort** [comment]
@marimp I'm unable to reproduce this on my Mac using Edge, Chrome, Firefox and Safari. Could you try upgrading your UI and Temporal Server versions? I looked at the differences between UI v2.7.0 and v2.7.1 and there were only some security patches done to our Docker images, so it doesn't seem like that would cause your issue.

If you wouldn't mind doing a screen recording of this issue and uploading it here, that would also be very much appreciated.

Thanks!

**Comment by marimp** [comment]
Hi @rossedfort,
I apologize for the late response but I miss the message.
I'm not able to reproduce the issue because I fixed it by replacing all special characters ":" with underscore and I also upgraded both temporal server and UI and all works fine.

So I think you can close the issue.
Great Thanks for your support
Regards
Marco

**Comment by jontro** [comment]
Hi, I am still having this issue in the web ui. 
<img width="1261" alt="image" src="https://github.com/temporalio/ui/assets/1257496/0168e151-7d5a-4c9b-85a6-c78fb78d5183">

Gives a 404 when going to the next step.

The link is encoded as following:
/workflows/BcEvent%2Fapi%2Fv2.0%2Fcompanies(145549f3-62f9-ed11-8848-000d3a466e14)%2Fitems(416d462d-05fa-ed11-8848-000d3a466e14)%2Fupdated/e6f98b62-dc80-4d6d-8104-41d301e09337/history

**Comment by mariawithpersona** [comment]
For us this started happening somewhere between UI version 2.22.3 and 2.23.0. The problematic character for us is `()`.
